- e2e/test_setcommitter.py
- guet/commands/setcommitters.py
- test/commands/test_setcommitters.py
When setting a committer, if the given initials aren't in the system, notify the user.
Connects #7 
```
guet init
guet set nonsense
No committer exists with initials 'nonsense'
```
Initialize guet, then attempt to set committers using initials that aren't registered.
> Error message when setting commiter not registered

- e2e/test_addcommitter.py
- e2e/test_commit_depends_on_last_pair_set.py
- e2e/test_setcommitter.py
- e2e/test_start.py
- guet/commands/addcommitter.py
- guet/commands/command.py
- guet/commands/help.py
- guet/commands/init.py
- guet/commands/setcommitters.py
- guet/commands/start.py
- guet/commit.py
- guet/gateways/gateway.py
- guet/gateways/io.py
- guet/stdin_manager.py
- guet/stdout_manager.py
- setup.py
- test/commands/test_addcommitter.py
- test/commands/test_help.py
- test/commands/test_init.py
- test/commands/test_setcommitters.py
- test/commands/test_start.py
- test/gateways/test_gateway.py
- test/gateways/test_io.py
- test/test_commit.py
- test/test_stdin_manager.py
Brief description of what this PR does, and why it is needed.
Connects #1 
In a project where you already have commit hooks, if you type `guet start`, you see
```
There is already commit hooks in this project. Would you like to overwrite (o), create (c) the file and put it in the hooks folder, or cancel (x)?
```
Initialize repository with a pre-commit hook, and attempt to start guet in the folder to get the prompt
```
git init
touch .git/hooks/pre-commit
guet init
guet start
There is already commit hooks in this project. Would you like to overwrite (o), create (c) the file and put it in the hooks folder, or cancel (x)?
```
If you answer with `o`, then check `pre-commit`, `commit-msg`, and `post-commit` to see if they're full as expected.
If you answer `c`, then check `guet-pre-commit`, …
> Manage situations where there are already hooks

- .github/CHANGELOG.md
Updates changelog to correctly say to use `pip3` instead of `pip`
> Update changelog to use pip3 instead of pip

- e2e/test_commit.py
- guet/config/get_current_committers.py
- guet/hooks/pre_commit.py
- test/hooks/test_pre_commit.py
Implements feature to block commits if `guet set` hasn't been done yet.
Fixes #28 
```
$ git init
$ guet start
$ git commit -m "Commit changes"
You must set your pairs before you can commit.
```
> Block commits without set

- e2e/dockertest/docker_test.py
- e2e/test_commit.py
- guet/config/get_current_committers.py
- guet/config/most_recent_committers_set.py
- guet/config/parse_comitters_set_line.py
- guet/config/set_current_committers.py
- test/config/test_get_current_committers.py
- test/config/test_most_recent_committers_set.py
- test/config/test_set_current_committers.py
Scopes a `guet set` to a particular repo.
Connects #17 
When considering `projectA` and `projectB`, the following workflow can be expected:
```
$ cd projectA
$ guet set cb
$ git commit -m "commit message"
$ cd ../projectB
$ git commit -m "commit message"
You must set committer
```
Because of the implementation, a `guet set` in `projectA` would overwrite a `guet set` in `projectB`, so on the next commit to `projectB` you would have to `guet set` again. Another issue has been opened to address multiple `guet sets` on a computer. Issue #34 tracks this problem.
> Scoped guet set

- e2e/test_version.py
- guet/factory.py
- test/test_factory.py
Adds flag for printing the version of `guet`.
Connects #36 
```
$ guet --version
2.2.0
```
Because of the implementation, putting `--version` on any command will print the version instead of doing whatever command was. For example `guet get current --version` will print `2.2.0`.
> Print version when the --version/-v flag is present

- e2e/test_commit.py
- guet/config/get_current_committers.py
- guet/config/set_current_committers.py
- guet/files/read_lines.py
- test/config/test_get_current_committers.py
- test/config/test_set_current_committers.py
- test/files/test_read_lines.py
Adds the ability to keep track of multiple `guet sets` in different projects. The corrects the implementation in #17.
Connects #34
```
$ cd projectA
$ guet set cb op
$ guet get current
Currently set committers
cb - chris boyer <chris@email.com>
op - other person <other@email.com>
$ cd ../projectB
$ guet set oop cb
$ guet get current
Currently set committers
cb - chris boyer <chris@email.com>
oop - other other person <otherother@email.com>
```
> Allow multiple guet sets at the same time between repos

- e2e/test_commit.py
- e2e/test_get.py
- e2e/test_setcommitter.py
- guet/commands/git_required_decorator.py
- guet/commands/start/factory.py
- guet/main.py
- test/commands/start/test_factory.py
- test/commands/test_git_required_decorator.py
Blocks running `guet set` in a folder that doesn't contain a git project.
Connects #37 
```
$ cd project
$ guet set cb aw
Git not initialized in this directory.
```
This error message is fine, but doesn't quite get at the route of the problem. A `guet start` is required for a `guet set` to be valuable. However, I'm am unconvinced that not having ran `guet start` should stop the user from setting the committers. It should, at the very least, warn you that you haven't started this repo for use with guet.
> Running set in non git folders

- e2e/test_errors.py
- guet/util/errors.py
- test/util/test_errors.py
Corrects error where every character in written to `.guet/errors` had a newline character appended to it.
Connects #42
```
$ guet command    # something that causes an error
An error has occurred, please refer to error logs for more information
$ cat ~/.guet/errors
Traceback (most recent call last):
...
```
The end-to-end test for this bug will fail if #33 is introduced. This is because at the time of implementation the easiest way to trigger a failure is to try and execute a command that guet cannot process (`guet fail`).
> Fix bug where stacktrace prints malformed in errors file

- guet/util/errors.py
- test/util/test_errors.py
Brief description of what this PR does, and why it is needed.
Connects #31 
Example of pull request in use in the following format:
```
$ guet invalid-command
An error has occurred, please refer to error logs (~/.guet/errors) for more information.
```
> Include path to the error file in the error message

- e2e/dockertest/docker_test.py
- e2e/test_addcommitter.py
- guet/commands/addcommitter/factory.py
- guet/commands/cancellable_strategy.py
- test/commands/addcommitter/test_factory.py
- test/commands/test_addcommitter.py
- test/commands/test_cancellable_strategy.py
When adding a new committer with the same initials as an already present committer, prompt the user if they want to overwrite it.
Connects #32
```
$ guet add initials "name1" name1@localhost
$ guet add initials "name2" name2@localhost
Matching initials "initials". Adding "name2" <name2@localhost> will
overwrite "name1" <name1@localhost>. Would you like to
continue (y) or cancel (x)?
y
$ guet get committers
All committers
initials - name2 <name2@email.com>
```
> Dont overwrite committers without warning

- e2e/test_commit.py
- guet/config/errors.py
- guet/config/most_recent_committers_set.py
- guet/hooks/pre_commit.py
- test/config/test_most_recent_committers_set.py
- test/hooks/test_pre_commit.py
Corrects an issue where upgrading from <2.3.0 would cause a breaking change unless you deleted your `committersset` file.
Connects #47
> Fix error where guet couldn't handle malformed committersset files

- e2e/test_get.py
- guet/commands/get/get_factory.py
Fixes a typo in the `guet get` help message.
Connects #63
> Fix type in guet get help message

- e2e/test_commit.py
- guet/hooks/commit_msg.py
- test/hooks/test_commit_msg.py
When committing with one committer, the co-authored line will not be added.
```
$ git commit -m "add some changes"
$ git log
commit 3887e100b63c0c7f433a579de372338582889263
Author: committer <committer@localhost>
Date:   Sat Mar 14 09:13:14 2020 -0400
add some changes
```
Before, there would have been a `Co-authored-by: committer <committer@localhost>` following `add some changes`.
> Don't add a 'Co-authored' line if there is only one committer

- .pylintrc
- e2e/dockertest/docker_test.py
- e2e/test_addcommitter.py
- guet/commands/addcommitter/add_committer_locally_strategy.py
- guet/commands/addcommitter/add_committer_strategy.py
- guet/commands/addcommitter/factory.py
- guet/committers/global_committer.py
- guet/committers/local_committer.py
- guet/config/add_committer.py
- guet/config/committer.py
- guet/config/committers.py
- guet/context/context.py
- setup.py
- test/commands/addcommitter/test_add_committer_local_strategy.py
- test/commands/addcommitter/test_add_committer_strategy.py
- test/commands/addcommitter/test_factory.py
- test/committers/test_global_committer.py
- test/committers/test_local_committer.py
- test/config/test_add_committer.py
- test/config/test_committers.py
- test/context/test_context.py
Adds the ability to save committers locally to a repository.
Connects #67 
```
$ guet add n1 name1 name1@test.com
$ guet add --local n1 other1 other1@test.com
Adding committer with initials "n1" shadows the global committer "n1" - "name1" <name1@test.com>
$ guet get committers
All committers
n1 - other1 <other1@test.com>
```
> Add --local flag to guet add

- e2e/test_setcommitter.py
- guet/commands/start_required_decorator.py
- test/commands/test_start_required_decorator.py
Displays a warning message when `guet set` is called from a folder without a `.git` folder.
Connects #69 
Example of pull request in use in the following format:
```
$ guet add n1 name1 name1@example.com
$ guet add n2 name2 name2@example.com
$ mkdir api
$ cd api
$ guet set n1 n2
You are not in a directory with a git folder. Change back
to your project's root directory.
```
> Print error message when running guet set from folder without git

- e2e/test_addcommitter.py
- guet/commands/usercommands/addcommitter/factory.py
- test/commands/usercommands/addcommitter/test_factory.py
When adding a local committer from a subfolder, configurations is added to the root directory of the project.
```
$ cd api/
$ guet add --local n1 name1 name1@example.com
```
A `.guet` directory with `name1`'s information will exist in the root directory of the project.
> guet add --local correctly handles being in a subfolder

- e2e/test_addcommitter.py
- e2e/test_removecommitter.py
- e2e/test_setcommitter.py
- guet/commands/usercommands/addcommitter/factory.py
- guet/commands/usercommands/remove/remove_strategy.py
- guet/commands/usercommands/setcommitters/set_committers_strategy.py
Ignore case of initials when adding, setting, or removing committers
Connects #60 
Example of pull request in use in the following format:
```
$ guet add INITIALS name email
$ guet set initials
$ guet remove INITIALS
```
All commands are processed as though "initials" was used.
> Ignore case of initials when adding, setting, or removing committers

- e2e/test_addcommitter.py
- e2e/test_setcommitter.py
- guet/commands/decorators/local_decorator.py
- guet/commands/decorators/start_required_decorator.py
- guet/commands/usercommands/addcommitter/add_committer_locally_strategy.py
- guet/committers/committers.py
- guet/main.py
- test/commands/decorators/test_local_decorator.py
- test/commands/usercommands/addcommitter/test_add_committer_local_strategy.py
- test/committers/test_committers.py
- test/committers/test_local_committer.py
Fixes bug where adding a committer locally that exactly matches a global committer won't create them locally.
```
$ guet add n "Name" name@example.com
$ guet add n "Name" name@example.com --local
$ cat .guet/committers
n,Name,name@example.com
```
> Local shadow add

- guet/git/hook.py
- test/git/test_hook.py
Since the default shebag is `#! /usr/bin/env python3`, the hooks won't work if the system doesn't have `python3` (such as on Windows when installing python3 the command is `python`).
Uses the `which()` utility in python to check if `python3` is available. If it's not, then it defaults to `python`. However, it won't check if `python` is installed.
> Change python shebang if python3 is not available

- e2e/test_addcommitter.py
- e2e/test_commit.py
- e2e/test_commit_changes_current_author.py
- e2e/test_get.py
- e2e/test_setcommitter.py
- e2e/test_start.py
- guet/commands/usercommands/get/committer_printing_strategy.py
- guet/commands/usercommands/get/get_factory.py
- guet/commands/usercommands/setcommitters/set_committers_strategy.py
- guet/commands/usercommands/start/create_alongside_hook_strategy.py
- guet/commands/usercommands/start/create_hook_strategy.py
- guet/commands/usercommands/start/hook_strategy.py
- guet/commands/usercommands/start/start_strategy.py
- guet/committers/__init__.py
- guet/committers/_comitters_printer.py
- test/commands/usercommands/setcommitters/test_set_committers_strategy.py
- test/committers/test_committers_printer.py
- test/context/test_context.py
Adds better success messages in the following instances:
- When user sets committers (in which case it prints the names of the set committers)
- When user starts guet tracking on a repository
Also adds a more detailed prompt for when a user guet starts in a repository that has commit hooks already.
> Better messages around commands

- e2e/test_start.py
- guet/git/_hook_loader.py
- test/git/test_git.py
Create hooks folder when it isn't already present.
Connects #80
```
$ rm -rf .git/hooks
$ guet start
No hooks directory found, creating one. 
guet successfully started in this repository.
```
> Create hooks folder when one is not present

- README.md
For some folks, looking at examples can be confusing depending on what special characters are used to indicate argument placeholders, so adding a short example might be helpful. Also fixes a minor typo. My prettier formatted the readme too. I think it just added some whitespace. 
Also fixes a minor typo. My prettier formatted the readme too. I think it just added some whitespace.
> Adds examples to readme

- .github/FAQ.md
I'm using guet and husky in a monorepo, and it took me a bit of troubleshooting to get it working. I'm hoping some additional examples in the FAQ might save someone the same effort.
Husky runs scripts in the same directory as package.json, so it can't find the .git folder to run guet hooks. However, if I try something like  this: `"post-commit": "../.git/hooks/pre-commit-guet"`  then one of the committers is the author and other committers are ignored. There is no error message.
I thought about making a feature request like _Support running guet from directories below repository root when guet is installed alongside other hooks_. But I think adding a couple examples to the readme is sufficient to enable people who want to script guet from outside of the root directory.
With the following …
> Update FAQ to cover using husky in monorepos

- .pre-commit-config.yaml
- e2e/dockertest/docker_test.py
- e2e/dockertest/file_system.py
- e2e/test_add_local.py
- e2e/test_get.py
- e2e/test_init.py
- e2e/test_setcommitter.py
- e2e/test_yeet.py
- guet/commands/yeet/__init__.py
- guet/commands/yeet/_remove_global.py
- guet/commands/yeet/_remove_local.py
- guet/commands/yeet/_yeet.py
- guet/files/_file.py
- guet/git/__init__.py
- guet/git/_all_guet_hooks.py
- guet/git/_all_valid_hooks.py
- guet/git/git.py
- guet/git/hook.py
- guet/hooks/_run.py
- guet/main.py
- guet/steps/preparation/initialize.py
- setup.py
- test/commands/yeet/test_remove_global.py
- test/commands/yeet/test_remove_local.py
- test/files/test_file.py
- test/git/test_all_guet_hooks.py
- test/step/preparation/test_initialize.py
Introduces a `guet yeet` command for the version 3.0 release which removes related guet files.
Connects #95 
```
$ guet init
$ ls .git/hooks
commit-msg pre-commit post-commit
$ guet yeet
$ ls .git/hooks
```
Also introduces a couple extra `isort` checks
> Add guet yeet command

- e2e/test_commit.py
- e2e/test_commit_changes_current_author.py
- guet/git/__init__.py
- guet/git/_append_coauthors.py
- guet/hooks/_commit_msg.py
- test/git/test_append_coauthors.py
- test/hooks/test_commit_msg.py
Fixes bug where commit message would be lost when co-authors were added to a commit.
> Preserve commit message
